### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by jsoref**
I understand that you don't use GitHub as a primary contribution mechanism.

This PR is actually too big for GitHub (its limit is 250 commits and this is 320 (it's actually relatively small all things considered). But it isn't the kind of thing I'd want to send as a patch series.

Generally, I offer to split/slice as a project requests (e.g. by module or change kind -- comments vs function vs api vs ui string ...). I'm also happy to drop directories / files if it turns out that a given set shouldn't be changed.

This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).

The misspellings have been reported at https://github.com/jsoref/pgpool2/commit/e580e1f39b627f68120a1e2c7659cc3e1f8086db#commitcomment-45235213

The action reports that the changes in this PR would make it happy: https://github.com/jsoref/pgpool2/commit/702c18b3c5291b32e20a387ff051297e761ddc1a

Note: this PR does not include the action. If you're interested in running a spell check on every PR and push, that can be offered separately.

### CODE REVIEW

**Comment by tatsuo-ishii** [comment]
Thanks for the PR. I have downloaded all PR as a single big patch file. I am going to look into the file, In the mean time I am doing the regression tests against master branch after applying the patch.

**Comment by jsoref** [comment]
Thanks, btw, are you aware that http://pgpool.net doesn't work? (it redirects and eventually triggers a redirect loop when it tries to load the wiki's main_page)

**Comment by tatsuo-ishii** [comment]
No, I didn't. Recently pgpool.net migrated to AWS. I will ask colleagues, who are in charge of maintaining the infrastructure, to  check it out. Thank you for letting know me.

**Comment by tatsuo-ishii** [comment]
Actually I have just tried to access http://pgpool.net and it seems it is properly redirected to https://pgpool.net/mediawiki/index.php/Main_Page. Any idea?

**Comment by jsoref** [comment]
Someone else said it works for them (they're in Europe, I'm in Canada), this is what I get in chrome:
image

It seems to work in curl (with `-L`).

Chrome has changed its cookie policy recently. It's possible that's relevant. But it's also possible it's a regional thing, the person in Europe for whom it's working now confirmed it was broken earlier.

**Comment by tatsuo-ishii** [comment]
I am not familiar with in this area (web things). I will report the error to my colleagues,

**Comment by tatsuo-ishii** [comment]
I have applied your typo fixes (along with Japanese doc fixes by me). Thank you!

**Pull request closed without merging**
