### PR TITLE
Replace Runtime.exec(String) with Runtime.exec(String[]) to avoid Java 21 deprecation warnings

### PR DESCRIPTION
**Pull request by vpa1977**
When running pgpool2 tests with Java 21, jdbc tests output deprecation warning when compiling PgpoolTest.java and RunTest.java. 
```
javac -Xlint:deprecation ./src/test/regression/tests/005.jdbc/*.java
./src/test/regression/tests/005.jdbc/PgpoolTest.java:59: warning: [deprecation] exec(String) in Runtime has been deprecated
	    proc = Runtime.getRuntime().exec(command_line);
	                               ^
./src/test/regression/tests/005.jdbc/RunTest.java:29: warning: [deprecation] exec(String) in Runtime has been deprecated
	    Process proc = Runtime.getRuntime().exec(command_line);
	                                       ^
2 warnings
```
Replace  Runtime.exec(String) with Runtime.exec(String[]) to avoid Java 21 deprecation warnings.

### CODE REVIEW

**Comment by pengbo0328** [comment]
@vpa1977 Thank you for creating this pull request.

I have tested your patch.
Your patch fixes deprecation warnings, but it causes the test failure.

The following is the result of the test.

```
$ cat tests/005.jdbc/testdir/result.txt
org.postgresql.util.PSQLException: ERROR: relation "autocommit" does not exist
  Position: 15
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
        at AutoCommitTest.do_test(AutoCommitTest.java:25)
        at RunTest.run(RunTest.java:41)
        at RunTest.main(RunTest.java:9)
```

**Comment by vpa1977** [comment]
Thank you! 
I have fixed the typo that was causing this issue. 

I was wondering if it would be ok to push commit that checks return code from waitFor() and prints psql's process stdout/stderr?

**Comment by pengbo0328** [comment]
@vpa1977 Thank you!

Now I got another error. Was I missing any settings?
```
java RunTest
autocommit: unknown error2
batch: unknown error2
column: unknown error2
lock: unknown error2
select: unknown error2
update: unknown error2
insert: unknown error2
CreateTempTable: unknown error2
PrepareThreshold: unknown error2
```

**Comment by pengbo0328** [comment]
@vpa1977 I've made a few minor changes to your patch and committed it bfee798e5045a309af2e297baed3d8544e68d4c2
Thank you for your patch!

**Comment by vpa1977** [comment]
> @vpa1977 I've made a few minor changes to your patch and committed it [bfee798](https://github.com/pgpool/pgpool2/commit/bfee798e5045a309af2e297baed3d8544e68d4c2) Thank you for your patch!

Thank you!!!!!!

**Pull request closed without merging**
